name: PHP-CS-Fixer

on:
  workflow_call:
    inputs:
      config_path:
        description: "Path to the PHP-CS-Fixer configuration file"
        type: string
        required: false
        default: ".php-cs-fixer.dist.php"

jobs:
  PHP-CS-Fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
      - name: Get extra arguments for PHP-CS-Fixer
        id: phpcs-intersection
        run: |
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr ' ' '\n')
          if ! echo "${CHANGED_FILES}" | grep -qE "^(\\.php-cs-fixer(\\.dist)?\\.php|composer\\.lock)$"; then
            EXTRA_ARGS=$(printf -- '--path-mode=intersection\n--\n%s' "${CHANGED_FILES}");
          else
            EXTRA_ARGS='';
          fi
          {
            echo "PHPCS_EXTRA_ARGS<<EOF"
            echo "$EXTRA_ARGS"
            echo "EOF"
          } >> "$GITHUB_ENV"
      - name: Run PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config="${{ inputs.config_path }}" -v --dry-run --stop-on-violation --using-cache=no
