name: Security-Composer

on:
    workflow_call:

jobs:
  Security-Composer:
    name: Security-Composer
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout ${{ github.repository }}"
        uses: actions/checkout@v4
        # - uses: actions/cache@v4
        #   id: cache-db
        #   with:
        #       path: ~/.symfony/cache
        #       key: db
      - name: Check composer dependencies
        uses: symfonycorp/security-checker-action@v5
